apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "authority.cb-interview.com"
    - "servicex.cb-interview.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "authority.cb-interview.com"
    - "servicex.cb-interview.com"
    tls:
      mode: SIMPLE
      credentialName: cb-tls
